### ISSUE TITLE
Can`t change audio stream

### ISSUE THREAD

**Issue by Uchaplin** [lowlevel-studios/Wiseplay-SDK#2]
Hi !
Some video include not one audio stream but your player don`t have possibility to change it.
Please correct it.

**Comment by waninkoko** [comment]
Hi, Wiseplay 5.3.0 and higher now allow to change the audio track without requiring a SDK update.

**Comment by Uchaplin** [comment]
Thanks !

**Comment by Uchaplin** [comment]
Now each time I need stop play and select stream. It`s not comfortable.  
can you make "preferred audio stream" like  in MX player ? User enter locale code : EN, ES ... and player before start select stream using this information.
