### ISSUE TITLE
preferred audio stream

### ISSUE THREAD

**Issue by Uchaplin** [lowlevel-studios/Wiseplay-SDK#3]
Now each time I need stop play and select audio stream. It`s not comfortable.
can you make "preferred audio stream" like in MX player ? User enter locale code : EN, ES ... and player before start select stream using this information.

**Comment by waninkoko** [comment]
Hello. This feature will be available soon. For now, the player will select the primary audio track automatically.

**Comment by Uchaplin** [comment]
ok. waiting to it. 
10X
